'use strict';

angular.module('myApp.controllers', [])
    .controller('CustomerListController', ['$scope', 'custDataService', function ($scope, custDataService) {

        custDataService.getAllCustomers()
            .then(function (data) {
                $scope.customers = data.results;
            })
            .catch(function (error) {
                console.log("Error calling api: " + error.message);
            });
    }]).controller('OrderListController', ['$scope', 'custDataService', function ($scope, custDataService) {
        //TODO
        $scope.orders = [{ 'DateOrdered': '11/11/2013', 'OrderNumber': '12345' }];

    }]).controller('EditCustomerController', ['$scope', '$location', '$routeParams', 'custDataService', function ($scope, $location, $routeParams, custDataService) {

        custDataService.getCustomerById($routeParams.customerId)
            .then(function (data) {
                //TODO - refactor to use fromEntityKey (which won't return results[0])
                $scope.customer = data.results[0];
            }).catch(function (error) {
                console.log("Error calling api: " + error.message);
            });

        $scope.cancel = function () {
            $scope.customer.entityAspect.rejectChanges(); //undo pending changes and reset entityState to "Unchanged"
            $location.path('/');
        };

        $scope.delete = function () {
            debugger;
            custDataService.deleteCustomer($scope.customer);
            $location.path('/');
        };

        $scope.canDelete = true;
        $scope.save = function () {
            custDataService.saveChanges();
            $location.path('/');
        };

    }]).controller('CreateCustomerController', ['$scope', '$location', 'custDataService', function ($scope, $location, custDataService) {

        $scope.cancel = function () {
            $location.path('/');
        };
        
        var customer = custDataService.newCustomer({ customerID: 'TEMP' }); //TEMP is a HACK - Can't create entity w/o ID and 'AutoGeneratedKeyType' is none
        customer.customerID = '';
        $scope.customer = customer;

        $scope.save = function () {
            custDataService.saveChanges();
            $location.path('/');
        };
    }]);